version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nodejs
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app/src
